# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b43523cbe074c2d3a1acfec88cab6a3e7c4dda25d7794a6fe28734139fa47b257a2f9bd5d89136e317e0023d9f8471cf05735b2f320de10f3e9feb386cd5edb

test:
  secret_key_base: 8a4507be26bb60e2569b8c33958b18f4fcd207949e4153dfc93c7c5e72b0bae2e5c8ad4d3eff9dd63868ab696168b992dc3a90b82cfcaa9869e5918365f90f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
